cart/urls.py
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_page'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('thank-you/', views.ThankYouView.as_view(), name='thanks'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-item/<pk>/', views.RemoveItemView.as_view(), name='remove-item'), 
    path('payment/', views.PaymentView.as_view(),  name='payment'),
    path('confirm-order/', view=views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('payment/stripe/', views.payment_process, name='payment-stripe'),    

]
app_name='cart'

ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('staff/', include('staff.urls')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('', views.HomePageView.as_view(), name='home'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

staff/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.StaffPageView.as_view(), name='staff_page'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/<pk>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<pk>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('promo/', views.PromoListView.as_view(), name='promo-list'),
    path('promo/create/', views.PromoCreateView.as_view(), name='promo-create'),
    path('promo/<pk>/update/', views.PromoUpdateView.as_view(), name='promo-update'),
    path('promo/<pk>/delete/', views.PromoDeleteView.as_view(), name='promo-delete'),

]

app_name = 'staff'

staff/models.py
from django.db import models

staff/forms.py
from django import forms
from cart.models import Product, PromoCode
from django_flatpickr.widgets import DateTimePickerInput


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'image', 'description', 'price', 'stock', 'available_sizes', 'available_colors', 'primary_categories','secondary_categories' ]


class PromoStaffForm(forms.ModelForm):

    class Meta:
        model = PromoCode       
        fields = ['code', 'discount_type', 'discount_value', 'start_date', 'expiry_date', 'minimum_order_amount'] 
        widgets = {
            'start_date': DateTimePickerInput(attrs={'class': 'form-control'}),
            'expiry_date': DateTimePickerInput(attrs={'class': 'form-control'}),
            }

        

staff/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from django.views import generic



from cart.models import Order, Product, PromoCode
from staff.forms import ProductForm, PromoStaffForm
from staff.mixins import StaffMixins


class StaffPageView(LoginRequiredMixin, StaffMixins, generic.ListView):
    template_name = 'staff/staff.html'
    queryset = Order.objects.filter(ordered=False).order_by('-ordered_date')

    paginated_by = 20
    context_object_name = 'orders'


class ProductListView(LoginRequiredMixin, StaffMixins, generic.ListView):
    template_name = 'staff/product_list.html'
    queryset = Product.objects.all()
    paginate_by = 10
    context_object_name = 'products'


class ProductCreateView(LoginRequiredMixin, StaffMixins, generic.CreateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm

    def get_success_url(self):
        return reverse('staff:product-list')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, StaffMixins, generic.UpdateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse('staff:product-list')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, StaffMixins, generic.DeleteView):
    template_name = 'staff/product_delete.html'
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse('staff:product-list')


class PromoListView(LoginRequiredMixin, StaffMixins, generic.ListView):
    template_name = 'staff/promo_list.html'
    queryset = PromoCode.objects.all()
    paginate_by = 10
    context_object_name = 'promocodes'


class PromoCreateView(LoginRequiredMixin, StaffMixins, generic.CreateView):
    template_name  = 'staff/promo_create.html'
    form_class = PromoStaffForm

    def get_success_url(self):
        return reverse('staff:promo-list')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

class PromoUpdateView(LoginRequiredMixin, StaffMixins, generic.UpdateView):
    template_name = 'staff/promo_create.html'
    form_class = PromoStaffForm
    queryset = PromoCode.objects.all()

    def get_success_url(self):
        return reverse('staff:promo-list')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
class PromoDeleteView(LoginRequiredMixin, StaffMixins, generic.DeleteView):
    template_name = 'staff/promo_delete.html'
    queryset = PromoCode.objects.all()

    def get_success_url(self): 
        return reverse('staff:promo-list')       

templates/staff/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}">Go back to products</a>
                <hr />
                <h4>Create a product</h4>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}

                      
                    <button type='submit' class='btn'>Submit</button>
  
                </form>
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/product_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form method="POST" style="max-width: 400px; margin: 0 auto;">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <p>confirm the removal of the product</p>
                    <button type='submit' class='btn btn-secondary' >Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/product_list.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff Portal - Products</h2>
                <a href="{% url 'staff:product-create' %}">Create a product</a>
                <div class="card">
                    <div class="card-body">
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Title.</th>
                                        <th>Price</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product in products %}
                                    <tr>
                                        <td>{{ product.title }}</td>
                                        <td>{{ product.get_price }}  ₽</td>
                                        <td>
                                            <a href="{{ product.get_update_url }}">Update</a>
                                            
                                            <a tabindex="0" class="btn btn-sm" role='button'
                                                data-html='true' data-toggle='popover' data-trigger='focus'
                                                title='Are you sure you want to delete this product?'
                                                data-content="<a href='{{ product.get_delete_url }}' class='confirm-delete'>Confirm</a>">
                                                x
                                            </a>

                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="3">You don't have any products</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
                
            </div>
        </div>
        
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

{% block scripts %}
<script>
    $(function () {
        $("[data-toggle=popover]").popover();
        // Обработчик клика по ссылке "Confirm"
        $(document).on('click', '.confirm-delete', function (e) {
            e.preventDefault(); // Предотвращаем переход по ссылке
            var deleteUrl = $(this).attr('href'); // Получаем URL удаления
            // Здесь можно добавить логику для подтверждения удаления, например, через AJAX
            window.location.href = deleteUrl; // Перенаправляем на URL удаления
        });
    });
</script>
{% endblock scripts %}

templates/staff/product_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}">Go back to products</a>
                <hr />
                <h4>Update product</a>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/promo_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'staff:promo-list' %}">Go back to promocodes</a>
                <hr />
                <h4>Create promo </h4>
                <form method="POST" enctype="multipart/form-data" style="width: 360px">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }}

                    <button type="submit" class="btn btn-secondary">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/promo_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <form method="POST" style="max-width: 400px; margin: 0 auto;">
                    {% csrf_token %}
                    {{form|crispy}}
                    <p>confirm the removal of the product</p>
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/staff/promo_list.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff Portal - Promo</h2>
                <a href="{% url 'staff:promo-create' %}">Create a promocode</a>
                <div class="card">
                    <div class="card-body">
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Code</th>
                                        <th>Discount type</th>
                                        <th>Discount value</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for promo in promocodes %}
                                    <tr>
                                        <td>{{ promo.code }}</td>
                                        <td>{{ promo.discount_type }}</td>
                                        <td>{{ promo.get_discount_display }}</td>
                                        
                                        <td>
                                            <a href="{% url 'staff:promo-update' pk=promo.pk %}">Update</a>
                                            
                                            <a tabindex="0" class="btn btn-sm" role='button'
                                                data-html='true' data-toggle='popover' data-trigger='focus'
                                                title='Are you sure you want to delete this product?'
                                                data-content="<a href='{% url 'staff:promo-delete' pk=promo.pk %}' class='confirm-delete'>Confirm</a>">
                                                x
                                            </a>

                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="3">You don't have any promocodes</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class='active'>
                                                    <span>
                                                    {{ i }}
                                                     <span class='sr-only'>(current)</span>
                                                    </span>
                                                </li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script>
    $(function () {
        $("[data-toggle=popover]").popover();
        // Обработчик клика по ссылке "Confirm"
        $(document).on('click', '.confirm-delete', function (e) {
            e.preventDefault(); // Предотвращаем переход по ссылке
            var deleteUrl = $(this).attr('href'); // Получаем URL удаления
            // Здесь можно добавить логику для подтверждения удаления, например, через AJAX
            window.location.href = deleteUrl; // Перенаправляем на URL удаления
        });
    });
</script>
{% endblock scripts %}

templates/staff/promo_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-16">
                <a href="{% url 'staff:promo-list' %}">Go back to promocodes</a>
                <h4>Update promo</h4>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/staff/staff.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff Portal</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                        </h5>
                        <hr />
                        <a href="{% url 'staff:product-list' %}">&#8226; Products</a>
                        <hr />

                        <a href="{% url 'staff:promo-list' %}">&#8226; Promo</a>
                        <hr />

                        <h5 class="card-title">Recent orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>User</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>{{ order.user.email }}</td>
                                        <td>{{ order.get_total_order_price }} ₽ </td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class='active'>
                                                    <span>
                                                    {{ i }}
                                                     <span class='sr-only'>(current)</span>
                                                    </span>
                                                </li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}