cart/urls.py
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_page'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('thank-you/', views.ThankYouView.as_view(), name='thanks'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-item/<pk>/', views.RemoveItemView.as_view(), name='remove-item'), 
    path('payment/', views.PaymentView.as_view(),  name='payment'),
    path('confirm-order/', view=views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('payment/stripe/', views.payment_process, name='payment-stripe'),    

]
app_name='cart'

ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('staff/', include('staff.urls')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('', views.HomePageView.as_view(), name='home'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/forms.py
import logging
from datetime import timezone
from django import forms

from django import forms
from django.contrib.auth import get_user_model

from .models import Product, PromoCode, SizeVariation, ColorVariation, OrderItem, Address
User = get_user_model()
logger = logging.getLogger(__name__)

class CartForm(forms.ModelForm):
    size = forms.ModelChoiceField(queryset=SizeVariation.objects.none(), required=False)
    color = forms.ModelChoiceField(queryset=ColorVariation.objects.none(), required=False)


    class Meta:
        model = OrderItem
        fields = ( 'color', 'size')

    def __init__(self, *args, **kwargs):
        self.product_id = kwargs.pop('product_id', None)
        product = Product.objects.get(id=self.product_id)
        super().__init__(*args, **kwargs)
        

        if product:
            size_options = {
                'clothing': ['XS', 'S', 'M', 'L', 'XL'],
                'shoes': ['36', '36.5', '37', '37.5', '38', '38.5', '39', '39.5', '40', '40.5', '41', '41.5', '42']
            }

            category_name = product.primary_categories.name.lower() if product.primary_categories else None

            if category_name == 'accessories':
                self.fields['size'].required = False
                self.fields['color'].required = False

                self.fields['size'].queryset = SizeVariation.objects.all()
                self.fields['color'].queryset = ColorVariation.objects.all()

                self.fields['size'].initial = SizeVariation.objects.get(name='one size')
                self.fields['color'].initial = ColorVariation.objects.get(name='one color')

                self.fields['size'].widget.attrs['disabled'] = 'disabled'
                self.fields['color'].widget.attrs['disabled'] = 'disabled'
                
            elif category_name in size_options:
                self.fields['size'].queryset = product.available_sizes.filter(name__in=size_options[category_name])
                self.fields['color'].queryset = product.available_colors.all()

            if category_name != 'accessories':
                self.fields['size'].required = True
                self.fields['color'].required = True      

        
class AddressForm(forms.Form):

    shipping_country = forms.ChoiceField(choices=Address.DELIVERY_COUNTRIES)
    shipping_city = forms.CharField(required=False)
    shipping_postcode = forms.CharField(required=False)

    shipping_address_1 = forms.CharField(required=False)

    selected_shipping_address = forms.ModelChoiceField(queryset=Address.objects.none(), required=False)

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id', None)
        super().__init__(*args, **kwargs)

        user = None
        shipping_address_queryset =  Address.objects.none()
        if user_id:
            try:
                user = User.objects.get(id=user_id, is_active=True)
                shipping_address_queryset = Address.objects.filter(user=user)
            except User.DoesNotExist:
                logger.warning(f"User  {user_id} not found or inactive in AddressForm")
                user = None
                shipping_address_queryset =  Address.objects.none()  

        if 'selected_shipping_address' in self.fields:
            self.fields['selected_shipping_address'].queryset = shipping_address_queryset

            if not shipping_address_queryset.exists():
                self.fields['selected_shipping_address'].initial = None


    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_1', None):
                self.add_error(
                    "shipping_address_1",
                    "Please fill in this field"
                )
            if not data.get('shipping_postcode', None):
                self.add_error(
                    "shipping_postcode",
                    "Please fill in this field",
                )
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")



class PromoCodeForm(forms.Form):
    code = forms.CharField(max_length=50, label='Промокод')


    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order', None)
        super().__init__(*args, **kwargs)

    def clean_code(self):
        code = self.cleaned_data.get('code')
        promo = PromoCode.objects.filter(code__iexact=code).first()
        if not promo or not promo.is_valid():
            raise forms.ValidationError("Промокод не найден или не действителен.")

        
        self.promo = promo  
        return code



class StripePaymentForm(forms.Form):
    selectedCard = forms.CharField()

cart/views.py
from datetime import datetime
from django.utils import timezone
from decimal import Decimal
from venv import logger

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse

from django.views.decorators.csrf import csrf_exempt
from ecom_project import settings
import stripe

from .forms import CartForm, AddressForm, PromoCodeForm, StripePaymentForm
from .models import OrderItem, Payment, Product, Category, Address, Order, PromoCode, StripePayment
from .utils import get_or_set_order_session

import json
from django.contrib.auth.decorators import login_required
stripe.api_key = settings.STRIPE_SECRET_KEY
from django.core.signing import Signer

#stripe.api_version = settings.STRIPE_API_VERSION

class ProductListView(generic.ListView):
    template_name = 'cart_templates/product_list.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.objects.all().order_by('-created')
        category = self.request.GET.get('category', None)

        if not category:
            return queryset
        return queryset.filter(
            Q(primary_categories__name=category) |
            Q(secondary_categories__name=category)
        ).distinct()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'categories': Category.objects.values('name')})
        return context


    
class ProductDetailView(generic.FormView):
    template_name = 'cart_templates/product_detail.html'
    form_class = CartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse('cart:cart_page')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['product_id'] = self.get_object().id

        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(product=product, color = form.cleaned_data['color'], size = form.cleaned_data['size'])

        if not item_filter.exists():
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()
        else:
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context


class IncreaseQuantityView(generic.View):
    @staticmethod
    def get(request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        if order_item.quantity < order_item.product.stock:
            order_item.quantity += 1
            order_item.save(update_fields=['quantity'])
        else:
            messages.info(request, 'Доступное количество товара достигнуто')  
         
        return redirect('cart:cart_page')
    

class DecreaseQuantityView(generic.View):
    @staticmethod
    def get(request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save(update_fields = ['quantity', ])
        return redirect('cart:cart_page')        


class RemoveItemView(generic.View):
    @staticmethod
    def get(request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect('cart:cart_page')


class CartView(generic.View):
    template_name = 'cart_templates/cart.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context['order'].promo_code = None
        context['order'].save()
        return render(request, self.template_name, context)
    
    def post(self, request):
        context = self.get_context_data()
        form = PromoCodeForm(request.POST, order=context['order'])

        if form.is_valid():
            promo_code = form.promo  # Полученный из формы промокод
            order = context['order']
            order.promo_code = promo_code
            order.save()
            context['discount'] = order.get_discount_amount()
            context['final_price'] = order.get_order_price_with_discount()
            context['promo_code_form'] = form
        else:
            context['promo_code_form'] = form
        return render(request, self.template_name, context)
    
    def get_context_data(self):
        order = get_or_set_order_session(self.request)

        return {
            "order": order,
            "order_items": order.items.all(),
            "promo_code_form": PromoCodeForm(order=order),
            "discount": order.get_discount_amount() or 0,
            "final_price": order.get_order_price_with_discount(),
        }            
        

    


class CheckoutView(generic.FormView):
    template_name = 'cart_templates/checkout.html'
    form_class = AddressForm

    def get_success_url(self):
        return reverse('cart:payment')

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)

        selected_shipping_address = form.cleaned_data.get(
            'selected_shipping_address'
        )

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                user=self.request.user,
                address_1=form.cleaned_data['shipping_address_1'],
                postcode=form.cleaned_data['shipping_postcode'],
                city=form.cleaned_data['shipping_city'],
            )
            order.shipping_address = address


        order.save()
        messages.info(self.request, "You have successfully added your addresses")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        if self.request.user.is_authenticated:
            try:
                user = self.request.user.__class__.objects.get(id=self.request.user.id, is_active=True)
                kwargs["user_id"] = user.id
            except self.request.user.__class__.DoesNotExist:
                logger.error(f"User  {self.request.user.id} not found in get_form_kwargs")
                kwargs["user_id"] = None  

        else:
            kwargs["user_id"] = None
        return kwargs


    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class PaymentView(generic.TemplateView):
    template_name: str = 'cart_templates/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        context['CALLBACK_URL'] = self.request.build_absolute_uri(
            location=reverse("cart:thanks")
        )
        
        return context




class ThankYouView(generic.TemplateView):
    template_name: str = 'cart_templates/thanks.html'


#страница заказа
class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name: str = 'order.html'
    queryset = Order.objects.all()
    context_object_name = 'order'


# для оплаты по PayPal
class ConfirmOrderView(generic.View):
    @staticmethod
    def post(request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)

        Payment.objects.create(
            order=order,
            successful=True,
            raw_response=json.dumps(body),
            amount=float(body["purchase_units"][0]["amount"]["value"]),
            payment_method=Payment.PAYPAL_PAYMENT_METHOD,
        )

        order.ordered = True
        order.ordered_date = timezone.now()
        order.save(update_fields=['ordered', 'ordered_date', ])

        return JsonResponse({"data": "Success"})
    
    @staticmethod
    def get(request, *args, **kwargs):
        return JsonResponse({"data": "This endpoint only accepts POST requests."}, status=405)
    



@login_required
def payment_process(request):
    order_id = request.session.get('order_signed_id', None)

    if order_id is None:
        return redirect('cart:cart')
    signer = Signer()
    try:
        order_id = int(signer.unsign(order_id))
        order = get_object_or_404(Order, id=order_id, ordered=False)
    except (Signer.BadSignature, ValueError):
        logger.warning("Invalid signed_id in payment")
        return redirect('cart:cart')
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(
                        reverse('cart:thanks'))

        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'line_items': []
        }

        order.ordered = True
        order.ordered_date = timezone.now()
        order.save(update_fields=['ordered', 'ordered_date', ])


        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.order.get_total_order_price()* Decimal(100)),
                    'currency': 'rub',
                    'product_data': {
                        'name': item.product.title,
                    },

templates/cart_templates/cart.html
{% extends "base.html" %}
{% load rubles_format %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-white py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0 ml-sm-n3 ml-md-n2 ml-lg-n2">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Cart</strong>
            </div>
        </div>
    </div>
</div>


<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="site-blocks-table">
                {% if order_items %}




                    <table>
                        <thead class="table-cart">
                            <tr>
                                <th >Image</th>
                                <th >Product</th>
                                <th >Price</th>
                                <th >Quantity</th>
                                <th >Total</th>
                                <th >Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td class="product-thumbnail text-center">
                                    <img src="{{ item.product.image.url }}" class="img-fluid" style="max-width: 100px; max-height: 100px;">
                                </td>
                                <td class="product-name text-center">
                                    <h2 class="h5 text-black">{{ item.product.title }}</h2>
                                    <small>Size: {{ item.size.name }} </small>
                                    <small>Color: {{ item.color.name }}</small>
                                </td>
                                <td class="text-center">{{ item.product.get_price|rubles_format }} ₽ </td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <a href="{% url 'cart:decrease-quantity' item.id %}"
                                                class="btn">
                                                &minus;
                                            </a>
                                        </div>
                                        <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                                        <div class="input-group-append">
                                            <a href="{% url 'cart:increase-quantity' item.id %} "
                                                class="btn">
                                                &plus;
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center">
                                    {{ item.get_total_item_price|rubles_format }} ₽ 
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'cart:remove-item' item.id %}"
                                        class="btn btn-sm">Delete</a>
                                </td>
                            </tr>


                            {% endfor %}
                        </tbody>
                    </table>

                    {% else %}
                    <p>There are no items in your cart.
                        <a href="{% url 'cart:product-list' %}">Continue shopping</a></p>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if order.items.count > 0 %}

        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-12">
                        <a class="btn  btn-sm btn-block"
                            href="{% url 'cart:product-list' %}">Continue shopping</a>
                    </div>
                </div>
            </div>

            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">Subtotal</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">{{ order.get_raw_total_order_price|rubles_format }} ₽ </strong>
                            </div>
                        </div>

                        
                            

                        <div class="row mb-3">
                            {% if discount > 0 %}
                            <div class="col-md-6">
                                <span class="text-black">Discount:</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">{{ discount }}₽</strong>
                            </div>

                            {% endif%}
                        </div>                    
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">{{ order.get_total_order_price|rubles_format }} ₽ </strong>
                            </div>
                        </div>

                        <div class="row mb-5">
                            <div class="col-md-12 ml-auto text-right">
                                <form method="post">
                                    {% csrf_token %}
                                    {{ promo_code_form|crispy }}
                                    <button type="submit" class="btn btn-secondary">Apply Promo Code</button>
                                </form>       
                            </div>
                        </div>


                        


                        <div class="row">
                            <div class="col-md-12">
                                <a class="btn btn-lg py-3 btn-block" href="{% url 'cart:checkout' %}">Proceed to checkout</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        {% endif %}

    </div>
</div>

{% include 'new_items.html' %}
{% endblock content %}

templates/cart_templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load rubles_format %}

{% block content %}

<div class="bg-white py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a><span class="mx-2 mb-0">/</span>
                <a href="{% url 'cart:cart_page' %}" class="text-black">Cart</a><span class="mx-2 mb-0">/</span>
                <strong class="text-black">Checkout</strong>
            </div>
        </div>
    </div>
</div>


<div class="site-section">
    <div class="container">
        {% if not request.user.is_authenticated %}
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="border p-4 rounded" role="alert">
                    You are nearly finished with your order.
                    To finalize your order, please <a href="{% url 'account_login' %}">Login</a> or 
                    <a href="{% url 'account_signup' %}">Signup</a>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 90%;" aria-valuenow="90"
                        aria-valuemin="0" aria-valuemax="100">90% complete</div>
                </div>
            </div>
        </div>
        {% else %}

        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-5 mb-md-0">
                    <h2 class="h3 mb-3 text-black text-center">Billing Details</h2>
                    <hr />
                    {{ form|crispy }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-lg py-3 btn-block">
                            Proceed to payment
                        </button>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <h2 class="h3 mb-3 text-black text-center">Your Order</h2>
                            <hr>
                            <div class="p-3 p-lg-5">
                                <table class="table site-block-order-table mb-5">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in order.items.all %}
                                        <tr>
                                            <td>
                                                {{ item.size.name }}, {{ item.colour.name }} {{ item.product.title }}
                                                <strong class="mx-2">x</strong> {{ item.quantity }}
                                            </td>
                                            <td>
                                                {{ item.get_total_item_price }}₽
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        <tr>
                                            <td><strong>Subtotal</strong></td>
                                            <td>{{ order.get_raw_total_order_price|rubles_format }}₽</td>
                                        </tr>
                                        <tr>
                                            <td><strong class="text-black font-weight-bold">Order Total</strong></td>
                                            <td>
                                                <strong class="text-black font-weight-bold">
                                                    {{ order.get_total_order_price|rubles_format }}₽
                                                </strong>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        {% endif %}
    </div>
</div>

{% endblock content %}

templates/cart_templates/payment.html
{% extends "base.html" %}
{% load rubles_format %}
{% block content %}



<div class='container'>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
                Your payment was successful.
            </div>
            <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
                Your payment failed. Please try again.
            </div>

            <div class="text-center py-3">
                <div id="loader" class="lds-ring" style="margin: auto; display: none;">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>

            <div id='paymentInfo'>
                <p>Order total: {{ order.get_total_order_price|rubles_format }} ₽ </p>
                <h4>Select a payment method</h4>

<!-- ссылка на payment_strip -->
                <div>
                    <a href="{% url 'cart:payment-stripe' %}" class="btn btn-primary btn-block mb-5">Stripe</a>
                </div>
                <div>
                    <a href="#" class="btn btn-primary btn-block mb-5">T-Bank</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/cart_templates/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-white py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">{{ product.title }}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6">
                <img src="{{ product.image.url }}" class="img-fluid">
            </div>
            <div class="col-md-6">
                <h2 class="text-black">{{ product.title }}</h2>
                <p>{{ product.description }}</p>

                {% if product.in_stock %}
                    {% if product.stock >= 10 %}
                        <p>Available stock: many </p>
                    {% else %}
                        <p>Available stock: {{ product.stock }} units</p>
                    {% endif %}


                    <form method="POST" class="form-product-detail">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type='submit' class="btn btn-secondary buy-now">Add to cart</button>
                    </form>


                {% else %}
                    <p>This item is out of stock</p>
                {% endif %}
                

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/cart_templates/thanks.html
{% extends "base.html" %}

{% block content %}
<div class="content">
    <div class="site-section">
        <div>
            <h2 style="display:flex; justify-content: center;">Thanks for your order </h2>
        </div>
    </div>    
</div>
{% endblock content %}