cart/urls.py
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_page'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('thank-you/', views.ThankYouView.as_view(), name='thanks'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-item/<pk>/', views.RemoveItemView.as_view(), name='remove-item'), 
    path('payment/', views.PaymentView.as_view(),  name='payment'),
    path('confirm-order/', view=views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('payment/stripe/', views.payment_process, name='payment-stripe'),    

]
app_name='cart'

ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('staff/', include('staff.urls')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('', views.HomePageView.as_view(), name='home'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

staff/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.StaffPageView.as_view(), name='staff_page'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/<pk>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<pk>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('promo/', views.PromoListView.as_view(), name='promo-list'),
    path('promo/create/', views.PromoCreateView.as_view(), name='promo-create'),
    path('promo/<pk>/update/', views.PromoUpdateView.as_view(), name='promo-update'),
    path('promo/<pk>/delete/', views.PromoDeleteView.as_view(), name='promo-delete'),

]

app_name = 'staff'

templates/base.html
{% load static %}
{% load cart_template_tags %}
{% load rubles_format %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title> Ecommercial cite {% block title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" type="text/css" rel="stylesheet">
</head>


<body>

<div class="site-wrap">
      {% include 'navbar.html' %}
      {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                  <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                  <span class="alert-inner--text">{{ message }}</span>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
          {% endfor %}
      {% endif %}

{% block content %}
{% endblock content %}

{% include 'footer.html' %}
</div> 

{% block scripts %}
{% endblock scripts %}

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const closeButtons = document.querySelectorAll('.alert .close');

    closeButtons.forEach(button => {
    button.addEventListener('click', (event) => {
     
      const alertElement = button.closest('.alert');
      if (alertElement) {
        
        alertElement.remove();
        
      }
    });
  });
});        
</script>

</body>
</html>

templates/bites.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'cart:product-list' %}">Shop</a></li>
            <li><a href="/contact">Contact</a></li>
            {% if request.user.is_staff %}
                <li><a href="{% url 'staff:staff_page' %}">Staff</a></li>
            {% endif %}
            <li>
                <a href="{% url 'cart:cart_page' %}" class="site-cart">
                    <span><i class="fas fa-shopping-cart"></i></span>
                    <span class="count">{{ request|cart_items_count }}</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

{% load  static %}

<nav class="navbar navbar-expand-sm navbar-light bg-light shadow">
 <a class="navbar-brand" href="/">
    Beast
 </a>
 <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarText">
   <ul class="navbar-nav mr-auto">
     <li class="nav-item">
       <a class="nav-link" href="/">Home</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="{% url 'cart:product-list' %}">Shop</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="/contact">Contact</a>
     </li>
   </ul>
   {% if request.user.is_staff %}
                <li><a href="{% url 'staff:staff_page' %}">Staff</a></li>
    {% endif %}
 </div>
</nav>





        
{% include 'navbar.html' %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
            <span class="alert-inner--text">{{ message }}</span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}


    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}



    cart/views 

    def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['order'] = get_or_set_order_session(self.request)
    context['order_items'] = context['order'].items.all()

    print("context['order_items']:", context['order_items'])

    for item in context['order_items']:
        print(f'Product: {item.product.title}, Quantity: {item.quantity}, Color: {item.color}, Size: {item.size}, Price: {item.get_raw_total_item_price()}')
    print('CART VIEW: ', context['order'], 'context : ', context)

    # работа с промокодом

    context['promo_code_form'] = PromocodeForm() 
    context['discount'] = 0  # Изначально скидка 0
    context['final_price'] = context['order'].get_total_order_price()

    if self.request.method == 'POST':
        promo_code_form = PromocodeForm(self.request.POST)
        print('promo_code_form: ', promo_code_form)
        if promo_code_form.is_valid():
            code = promo_code_form.cleaned_data['code']
            promo_code = self.get_valid_promo_code(code)
            print('code: ', code, 'promo_code: ', promo_code)
            if promo_code:
                print('if promo_code')
                context['discount'] = self.calculate_discount(promo_code, context['order'].get_total_price())
                context['final_price'] -= context['discount'] 
                print("context['final_price']", context['final_price'])

    return context


def get_valid_promo_code(self, code):
    try:
        promo_code = PromoCode.objects.get(code=code)
        if promo_code.is_valid():
            return promo_code
    except PromoCode.DoesNotExist:
        return None
def calculate_discount(self, promo_code, total_price):
    if promo_code.discount_type == 'fixed':
        return min(promo_code.discount_value, total_price)  # Не превышаем общую сумму
    elif promo_code.discount_type == 'percent':
        return total_price * promo_code.discount_value / 100
    return 0


cart.py forms

class PromocodeForm(forms.ModelForm):
    code = forms.CharField(max_length=50, label='Промокод')
    class Meta:
        model = PromoCode
        fields = ('code',)

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order', None)  # Передаём заказ в форму
        super().__init__(*args, **kwargs)

    def clean_code(self):
        code = self.cleaned_data.get('code')

        print('PromocodeForm code: ', code)

        try:
            promo = PromoCode.objects.filter(code__iexact=code)
            if promo.exists():
                promo = promo.first()
            else: 
                raise forms.ValidationError("Промокод не найден.")      
        except PromoCode.DoesNotExist:
            raise forms.ValidationError("Промокод не найден.")    


        
        self.promo = promo  # Сохраняем для использования позже
        return code



        get_context_data, order:  order - 10 - admin - 15percent (15%)
  


        def post:  {'order': <Order: order - 10 - admin - 15percent (15%)>, 'order_items': <QuerySet [<OrderItem: 1 x Wool pants>]>, 'promo_code_form': <PromocodeForm bound=False, valid=Unknown, fields=(code)>, 'discount': 3150, 'final_price': 17850}
        
        PromocodeForm code:  15percent

        get_total_order_price: > 0 , is not None 17850

        form is valid: promo_code:  15percent (15%) order:  order - 10 - admin - 15percent (15%) 
        context:  {'order': <Order: order - 10 - admin - 15percent (15%)>, 'order_items': <QuerySet [<OrderItem: 1 x Wool pants>]>, 'promo_code_form': <PromocodeForm bound=True, valid=True, fields=(code)>, 'discount': 3150, 'final_price': 17850}

        MODEL- get_discount_amount - total:  21000 self.promo_code:  15percent (15%)

        self.promo_code.discount_type == 'percent': -- 21000 self.promo_code.discount_value: 15
        
        percent:  3150

        
        if order_id is not None:
        try: 
        order, _ = Order.objects.get_or_create(id=order_id, ordered=False)
        request.session['order_id'] = order.id

    else:
        order = Order.objects.create()
        request.session['order_id'] = order.id

    if request.user.is_authenticated and order.user is None:
        order.user = request.user
        order.save(update_fields=['user', ])

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-white py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0" style="margin-left: -60px;">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Contact</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Get in touch</h2>
            </div>
            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn button-style btn-lg btn-block" value="Submit message" />
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/footer.html
{% load crispy_forms_tags %}


<footer class="site-footer border-top">

    <section class="">
        <div class="container text-center text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                <p>Questions? Go ahead.</p>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-light mt-4" value="Submit message" />
                </form>
            </div>-->
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Products
              </h6>

              <p>
                <a href="#!" class="text-reset">About us</a>
              </p>
              <p>
                <a href="#!" class="text-reset">FAQ</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Contact</a>
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Useful links about project
              </h6>
              <p>
                <a href="#!" class="text-reset">Privacy</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Delivery</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Returns</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Size quide</a>
              </p>
            </div>
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
              <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                info@example.com
              </p>
              <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
              <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>


      <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <p>
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This website is made with <i class="fas fa-heart"> Django</i>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content%}

<header>   
    <div class="header-image">
      <img src="/media/images/main_page_wallpaper.jpg" alt="Image" class="fullscreen-img" >
    </div>

</header>

{% endblock %}

templates/navbar.html
{% load static %}
{% load cart_template_tags %}

<nav class="navbar navbar-expand-md navbar-light bg-light ">
    <div class="container-brand">
        <a class="navbar-brand" href="/">BEAST</a>
    </div>
    <!--кнопка для навигационного меню с маленьким экраном-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  
    

    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent" style="width: 100%">
        <ul class="navbar-nav ">
            <li class="nav-item ">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:product-list' %}">Shop</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" style='color:red' href="#">Sale</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="#">Journal</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>

            {% if request.user.is_staff %}
            <li class="nav-item">
                <a class='nav-link' href="{% url 'staff:staff_page' %}">Staff</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="collapse navbar-collapse justify-content-end" style="width: 15%">
        <ul class="navbar-nav ">
            <li class="nav-item ">
                <a href="{% url 'cart:cart_page' %}" class="nav-link">

                    <img src="/media/icons/корзина.png" alt="Корзина" class="icon" style="max-width: 20px; max-height: 20px;">
                    {{ request|cart_items_count }}
                </a>
            </li>   
            
            {% if user.is_authenticated %}
            <li class="nav-item mr-auto">
                <a class='nav-link' href="{% url 'account_logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item mr-auto">
                <a class='nav-link' href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>


</nav>    

templates/new_items.html
{% load static %}


<div class="site-section">
  <div class="container-new-product">
  <p class="text-center">New Products</p>
    <div class="products-grid ">
      {% for product in new_items %}
      <div class="product-card" style="  text-align: center;">
          <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="img-fluid custom-fit"></a>
          <a href="{{ product.get_absolute_url }}" class="product-name no-underline">
              <p>{{ product.title }}</p>
          </a>
          <p>{{ product.description}}</p>
          
      </div>
      {% endfor %}
    </div>
  </div>
</div>  

templates/order.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'profile' %}">Back to profile</a>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            Order: #{{ order.reference_number }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">Ordered on: {{ order.ordered_date }}</h6>
                        <hr />
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Product.</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.items.all %}
                                    <tr>
                                        <td>{{ item.size.name }}, {{ item.colour.name }} of {{ item.product.title }} x
                                            {{ item.quantity }}</td>
                                        <td>{{ item.get_total_item_price }}  ₽ </td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td>Subtotal</td>
                                        <td>{{ order.get_order_price_with_discount }} ₽ </td>
                                    </tr>
                                    <tr>
                                        <td>Total</td>
                                        <td>{{ order.get_total_order_price }} ₽ </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% load rubles_format %}
{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Your profile</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                            <a href="{% url 'account_logout' %}">
                                <small class="float-right">Logout</small></a>
                        </h5>
                        <hr />
                        <h5 class="card-title">Your orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>{{ order.get_total_order_price|rubles_format }} ₽ </td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/scripts.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>